### ISSUE TITLE
qw without paranthesis errors

### ISSUE THREAD

**Issue by eserte** [jozef/Module-Build-SysPath#5]
qw without paranthesis is now a hard error in perl 5.18 and 5.20, and this is causing the test suite to fail.

**Comment by nichtich** [comment]
Please fix or refactor Debian::Apt::PM to not require this module!

**Comment by jozef** [comment]
fixed in 2665f55e6f6e0ce0cacbdf2dbd6ec719d6407a94
0.17 uploaded to CPAN
